name: Flutter Build APK (android debug)
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  run-flutter-test:
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.3
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - name: Run Flutter doctor
        run: flutter doctor
      - name: Run Flutter Test
        run: flutter test
  run-flutter-build:
    needs: run-flutter-test
    runs-on: macos-latest
    outputs:
        apk-file: ${{ steps.publish-apk.outputs.apk-file }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.3
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - name: Run Flutter doctor
        run: flutter doctor
      - name: Run Flutter Build (android)
        run: flutter build apk --debug
      - name: Publish apk name
        id: publish-apk
        run: find build/app/outputs/flutter-apk/*.apk -type f -execdir echo 'apk-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: build/app/outputs/flutter-apk
  get-flutter-build:
      needs: run-flutter-build
      runs-on: macos-latest
      steps:
        - name: Get build Artifacts
          uses: actions/download-artifact@v4
          with:   
            name: build-assets
        - name: Output the build-assets contents
          run: ls
        - name: Output apk file name
          run: echo "${{ needs.run-flutter-build.outputs.apk-file }}"
