name: Flutter Build APK (android debug)
on: [push, workflow_dispatch]
jobs:
  run-flutter-test:
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.3
      - name: Run Flutter doctor
        run: flutter doctor
      - name: Run Flutter Test
        run: flutter test
  run-flutter-build:
    needs: run-flutter-test
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.3
      - name: Run Flutter doctor
        run: flutter doctor
      - name: Run Flutter Build (android)
        run: flutter build apk --debug
