name: Flutter Build APK (android debug)
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
env:
  FLUTTER_VERSION: 3.19.3
  APP_KEY_STORE: ${{ secrets.APP_KEY_STORE }}
jobs:
  run-flutter-test:
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: /Users/runner/hostedtoolcache/flutter/stable-${{ env.FLUTTER_VERSION }}-arm64
          key: ${{ runner.OS }}-flutter-install-cache-${{ '/Users/runner/hostedtoolcache/flutter/stable-${{ env.FLUTTER_VERSION }}-arm64' }}
          save-always: true
      - uses: subosito/flutter-action@v1
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Run Flutter doctor
        run: flutter doctor
      - name: Run Flutter Test
        id: run-tests
        run: flutter test --file-reporter json:reports/tests.json
      - name: Upload Test Report 
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/tests.json
  run-flutter-build:
    needs: run-flutter-test
    runs-on: macos-latest
    outputs:
        apk-file: ${{ steps.publish-apk.outputs.apk-file }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: /Users/runner/hostedtoolcache/flutter/stable-${{ env.FLUTTER_VERSION }}-arm64
          key: ${{ runner.OS }}-flutter-install-cache-${{ '/Users/runner/hostedtoolcache/flutter/stable-${{ env.FLUTTER_VERSION }}-arm64' }}
          save-always: true
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
      # OPTIONAL WORK
      # - name: Run Flutter doctor
      #   run: flutter doctor 
      - name: Run Flutter Build (android)
        run: flutter build apk --debug
      - name: Publish apk name
        id: publish-apk
        run: find build/app/outputs/flutter-apk/*.apk -type f -execdir echo 'apk-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: build/app/outputs/flutter-apk
  get-flutter-build:
      needs: run-flutter-build
      runs-on: macos-latest
      steps:
        - name: Get build Artifacts
          uses: actions/download-artifact@v4
          with:   
            name: build-assets
        - name: Output the build-assets contents
          run: ls
        - name: Output apk file name
          run: echo "${{ needs.run-flutter-build.outputs.apk-file }}"
        - name: Show secret 
          run: echo "APP_KEY_STORE -> ${{ secrets.APP_KEY_STORE }}"
